## DATA LOADING AND CLEANING

In [1]:
import pandas as pd
import numpy as np

In [2]:
# Avoid unnecessary warnings, (EX: software updates, version mismatch, and so on.)
import warnings
warnings.filterwarnings('ignore')

In [3]:
df=pd.read_csv('CYBER.csv')

In [4]:
df.head()

,'Flow Duration','Tot Fwd Pkts','Tot Bwd Pkts','TotLen Fwd Pkts','TotLen Bwd Pkts','Fwd Pkt Len Max','Fwd Pkt Len Min','Fwd Pkt Len Mean','Fwd Pkt Len Std','Bwd Pkt Len Max',...,'Fwd Act Data Pkts','Active Mean','Active Std','Active Max','Active Min','Idle Mean','Idle Std','Idle Max','Idle Min',Label
0,1518,2,5,110,377,110,0,55.0,77.7817,377,...,1,0,0,0,0,0,0,0,0,Brute_Force
1,5894,4,8,168,4498,168,0,42.0,84.0000,1460,...,1,0,0,0,0,0,0,0,0,Brute_Force
2,272,1,1,0,0,0,0,0.0,0.0000,0,...,0,0,0,0,0,0,0,0,0,Brute_Force
3,2611,4,8,322,4434,322,0,80.5,161.0000,1460,...,1,0,0,0,0,0,0,0,0,Brute_Force
4,294,1,1,0,0,0,0,0.0,0.0000,0,...,0,0,0,0,0,0,0,0,0,Brute_Force

In [5]:
df.tail()

,'Flow Duration','Tot Fwd Pkts','Tot Bwd Pkts','TotLen Fwd Pkts','TotLen Bwd Pkts','Fwd Pkt Len Max','Fwd Pkt Len Min','Fwd Pkt Len Mean','Fwd Pkt Len Std','Bwd Pkt Len Max',...,'Fwd Act Data Pkts','Active Mean','Active Std','Active Max','Active Min','Idle Mean','Idle Std','Idle Max','Idle Min',Label
128794,68942,3,2,517,0,517,0,172.3333,298.4901,0,...,1,0,0,0,0,0,0,0,0,Normal
128795,63327,2,2,1277,1356,1277,0,638.5000,902.9754,1356,...,1,0,0,0,0,0,0,0,0,Normal
128796,139061,3,3,517,0,517,0,172.3333,298.4901,0,...,1,0,0,0,0,0,0,0,0,Normal
128797,21641848,2,5,0,1,0,0,0.0000,0.0000,1,...,0,3242118,0,3242118,3242118,10100000,0,10100000,10100000,Normal
128798,248023,0,2,0,0,0,0,0.0000,0.0000,0,...,0,0,0,0,0,0,0,0,0,Normal

In [6]:
df.shape

(128799, 67)

In [7]:
df.size

8629533

In [8]:
df.columns

Index([''Flow Duration'', ''Tot Fwd Pkts'', ''Tot Bwd Pkts'',
       ''TotLen Fwd Pkts'', ''TotLen Bwd Pkts'', ''Fwd Pkt Len Max'',
       ''Fwd Pkt Len Min'', ''Fwd Pkt Len Mean'', ''Fwd Pkt Len Std'',
       ''Bwd Pkt Len Max'', ''Bwd Pkt Len Min'', ''Bwd Pkt Len Mean'',
       ''Bwd Pkt Len Std'', ''Flow Byts/s'', ''Flow Pkts/s'',
       ''Flow IAT Mean'', ''Flow IAT Std'', ''Flow IAT Max'', ''Flow IAT Min'',
       ''Fwd IAT Tot'', ''Fwd IAT Mean'', ''Fwd IAT Std'', ''Fwd IAT Max'',
       ''Fwd IAT Min'', ''Bwd IAT Tot'', ''Bwd IAT Mean'', ''Bwd IAT Std'',
       ''Bwd IAT Max'', ''Bwd IAT Min'', ''Bwd PSH Flags'', ''Bwd URG Flags'',
       ''Fwd Header Len'', ''Bwd Header Len'', ''Fwd Pkts/s'', ''Bwd Pkts/s'',
       ''Pkt Len Min'', ''Pkt Len Max'', ''Pkt Len Mean'', ''Pkt Len Std'',
       ''Pkt Len Var'', ''FIN Flag Cnt'', ''SYN Flag Cnt'', ''RST Flag Cnt'',
       ''PSH Flag Cnt'', ''ACK Flag Cnt'', ''URG Flag Cnt'',
       ''CWE Flag Count'', ''ECE Flag Cnt'', ''Down/Up Ratio'',
       ''Pkt Size Avg'', ''Fwd Seg Size Avg'', ''Bwd Seg Size Avg'',
       ''Subflow Fwd Pkts'', ''Subflow Fwd Byts'', ''Subflow Bwd Pkts'',
       ''Subflow Bwd Byts'', ''Init Bwd Win Byts'', ''Fwd Act Data Pkts'',
       ''Active Mean'', ''Active Std'', ''Active Max'', ''Active Min'',
       ''Idle Mean'', ''Idle Std'', ''Idle Max'', ''Idle Min'', 'Label'],
      dtype='object')

In [9]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 128799 entries, 0 to 128798
Data columns (total 67 columns):
 #   Column               Non-Null Count   Dtype
---  ------               --------------   -----
 0   'Flow Duration'      128799 non-null  int64
 1   'Tot Fwd Pkts'       128799 non-null  int64
 2   'Tot Bwd Pkts'       128799 non-null  int64
 3   'TotLen Fwd Pkts'    128799 non-null  int64
 4   'TotLen Bwd Pkts'    128799 non-null  int64
 5   'Fwd Pkt Len Max'    128799 non-null  int64
 6   'Fwd Pkt Len Min'    128799 non-null  int64
 7   'Fwd Pkt Len Mean'   128799 non-null  float64
 8   'Fwd Pkt Len Std'    128799 non-null  float64
 9   'Bwd Pkt Len Max'    128799 non-null  int64
 10  'Bwd Pkt Len Min'    128799 non-null  int64
 11  'Bwd Pkt Len Mean'   128799 non-null  float64
 12  'Bwd Pkt Len Std'    128799 non-null  float64
 13  'Flow Byts/s'        128799 non-null  float64
 14  'Flow Pkts/s'        128799 non-null  float64
 15  'Flow IAT Mean'      128799 non-null  float64
 16  'Flow IAT Std'       128799 non-null  float64
 17  'Flow IAT Max'       128799 non-null  int64
 18  'Flow IAT Min'       128799 non-null  int64
 19  'Fwd IAT Tot'        128799 non-null  int64
 20  'Fwd IAT Mean'       128799 non-null  float64
 21  'Fwd IAT Std'        128799 non-null  float64
 22  'Fwd IAT Max'        128799 non-null  int64
 23  'Fwd IAT Min'        128799 non-null  int64
 24  'Bwd IAT Tot'        128799 non-null  int64
 25  'Bwd IAT Mean'       128799 non-null  float64
 26  'Bwd IAT Std'        128799 non-null  float64
 27  'Bwd IAT Max'        128799 non-null  int64
 28  'Bwd IAT Min'        128799 non-null  int64
 29  'Bwd PSH Flags'      128799 non-null  int64
 30  'Bwd URG Flags'      128799 non-null  int64
 31  'Fwd Header Len'     128799 non-null  int64
 32  'Bwd Header Len'     128799 non-null  int64
 33  'Fwd Pkts/s'         128799 non-null  float64
 34  'Bwd Pkts/s'         128799 non-null  float64
 35  'Pkt Len Min'        128799 non-null  int64
 36  'Pkt Len Max'        128799 non-null  int64
 37  'Pkt Len Mean'       128799 non-null  float64
 38  'Pkt Len Std'        128799 non-null  float64
 39  'Pkt Len Var'        128799 non-null  float64
 40  'FIN Flag Cnt'       128799 non-null  int64
 41  'SYN Flag Cnt'       128799 non-null  int64
 42  'RST Flag Cnt'       128799 non-null  int64
 43  'PSH Flag Cnt'       128799 non-null  int64
 44  'ACK Flag Cnt'       128799 non-null  int64
 45  'URG Flag Cnt'       128799 non-null  int64
 46  'CWE Flag Count'     128799 non-null  int64
 47  'ECE Flag Cnt'       128799 non-null  int64
 48  'Down/Up Ratio'      128799 non-null  int64
 49  'Pkt Size Avg'       128799 non-null  float64
 50  'Fwd Seg Size Avg'   128799 non-null  float64
 51  'Bwd Seg Size Avg'   128799 non-null  float64
 52  'Subflow Fwd Pkts'   128799 non-null  int64
 53  'Subflow Fwd Byts'   128799 non-null  int64
 54  'Subflow Bwd Pkts'   128799 non-null  int64
 55  'Subflow Bwd Byts'   128799 non-null  int64
 56  'Init Bwd Win Byts'  128799 non-null  int64
 57  'Fwd Act Data Pkts'  128799 non-null  int64
 58  'Active Mean'        128799 non-null  int64
 59  'Active Std'         128799 non-null  int64
 60  'Active Max'         128799 non-null  int64
 61  'Active Min'         128799 non-null  int64
 62  'Idle Mean'          128799 non-null  int64
 63  'Idle Std'           128799 non-null  int64
 64  'Idle Max'           128799 non-null  int64
 65  'Idle Min'           128799 non-null  int64
 66  Label                128799 non-null  object
dtypes: float64(20), int64(46), object(1)
memory usage: 65.8+ MB

In [10]:
df['Label'].unique()

array(['Brute_Force', 'HTTP_DDoS', 'ICMP_Flood', 'Normal', 'Port_Scan',
       'Web_Crwling'], dtype=object)

In [11]:
# Transform the columns value(ex: int to str, str to int) for classification purpose.
from sklearn.preprocessing import LabelEncoder
le = LabelEncoder()

var = ['Label']
  
for i in var:
    df[i] = le.fit_transform(df[i]).astype(int)

In [12]:
df.isnull().head()

,'Flow Duration','Tot Fwd Pkts','Tot Bwd Pkts','TotLen Fwd Pkts','TotLen Bwd Pkts','Fwd Pkt Len Max','Fwd Pkt Len Min','Fwd Pkt Len Mean','Fwd Pkt Len Std','Bwd Pkt Len Max',...,'Fwd Act Data Pkts','Active Mean','Active Std','Active Max','Active Min','Idle Mean','Idle Std','Idle Max','Idle Min',Label
0,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
1,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
2,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
3,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
4,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False

In [13]:
df = df.dropna()

In [14]:
# Describing the dataset in terms of non-null,avg,std deviation,min,max and percentile.
df.describe()

,'Flow Duration','Tot Fwd Pkts','Tot Bwd Pkts','TotLen Fwd Pkts','TotLen Bwd Pkts','Fwd Pkt Len Max','Fwd Pkt Len Min','Fwd Pkt Len Mean','Fwd Pkt Len Std','Bwd Pkt Len Max',...,'Fwd Act Data Pkts','Active Mean','Active Std','Active Max','Active Min','Idle Mean','Idle Std','Idle Max','Idle Min',Label
count,1.287990e+05,128799.000000,128799.000000,1.287990e+05,1.287990e+05,128799.000000,128799.000000,128799.000000,128799.000000,128799.000000,...,128799.000000,1.287990e+05,1.287990e+05,1.287990e+05,1.287990e+05,1.287990e+05,1.287990e+05,1.287990e+05,1.287990e+05,128799.000000
mean,1.211434e+07,32.137959,17.094845,2.857377e+04,5.774828e+03,154.251695,19.660137,55.290373,65.647581,561.156073,...,26.641061,5.065479e+05,1.671700e+05,6.843067e+05,3.665977e+05,3.319407e+06,2.707912e+05,3.522649e+06,3.078633e+06,1.014767
std,3.313302e+07,1520.942030,638.085907,2.053612e+06,6.522189e+05,285.115280,90.359819,110.086964,115.025425,687.521491,...,1515.541208,4.275231e+06,1.868728e+06,5.379069e+06,3.818159e+06,1.292889e+07,2.487136e+06,1.348547e+07,1.254057e+07,1.533043
min,0.000000e+00,0.000000,1.000000,0.000000e+00,0.000000e+00,0.000000,0.000000,0.000000,0.000000,0.000000,...,0.000000,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000
25%,5.085500e+03,1.000000,1.000000,0.000000e+00,0.000000e+00,0.000000,0.000000,0.000000,0.000000,0.000000,...,0.000000,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000
50%,8.609000e+03,2.000000,1.000000,3.300000e+01,2.000000e+01,20.000000,0.000000,20.000000,0.000000,20.000000,...,1.000000,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000
75%,2.230700e+04,4.000000,8.000000,3.200000e+02,4.434000e+03,318.000000,0.000000,79.750000,159.000000,1460.000000,...,1.000000,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,3.000000
max,1.200000e+08,138705.000000,157544.000000,1.880454e+08,2.136112e+08,63732.000000,1460.000000,13808.485700,23605.095200,4164.000000,...,138705.000000,1.131062e+08,7.025067e+07,1.131062e+08,1.131062e+08,1.199988e+08,6.159200e+07,1.199988e+08,1.199988e+08,5.000000

In [15]:
df.corr().head()

,'Flow Duration','Tot Fwd Pkts','Tot Bwd Pkts','TotLen Fwd Pkts','TotLen Bwd Pkts','Fwd Pkt Len Max','Fwd Pkt Len Min','Fwd Pkt Len Mean','Fwd Pkt Len Std','Bwd Pkt Len Max',...,'Fwd Act Data Pkts','Active Mean','Active Std','Active Max','Active Min','Idle Mean','Idle Std','Idle Max','Idle Min',Label
'Flow Duration',1.000000,0.061437,0.061538,0.044124,0.015069,-0.051395,0.089602,-0.000059,-0.147688,-0.209068,...,0.054246,0.328386,0.278617,0.364586,0.252943,0.597484,0.272177,0.610918,0.566649,0.472349
'Tot Fwd Pkts',0.061437,1.000000,0.686328,0.996086,0.064448,0.058389,0.003644,0.160044,-0.007123,0.012800,...,0.996414,0.031766,0.009162,0.028368,0.032185,-0.002758,-0.000691,-0.002677,-0.002700,0.024736
'Tot Bwd Pkts',0.061538,0.686328,1.000000,0.632510,0.754492,0.048681,0.000884,0.103008,-0.002700,0.016382,...,0.633878,0.019429,0.003561,0.016750,0.020672,-0.003057,-0.000832,-0.002977,-0.002992,0.024320
'TotLen Fwd Pkts',0.044124,0.996086,0.632510,1.000000,-0.000064,0.058699,0.003423,0.162232,-0.004268,0.014783,...,0.999682,0.024077,0.002548,0.019915,0.026210,-0.002622,-0.001151,-0.002670,-0.002491,0.017914
'TotLen Bwd Pkts',0.015069,0.064448,0.754492,-0.000064,1.000000,0.010551,-0.001719,-0.000800,0.001597,0.010400,...,0.000130,0.003616,0.001896,0.003705,0.003379,0.000149,0.000310,0.000268,0.000126,0.006927

In [16]:
pd.crosstab(df["'Tot Fwd Pkts'"], df["'Tot Bwd Pkts'"]).head()

'Tot Bwd Pkts',1,2,3,4,5,6,7,8,9,10,...,30658,31102,32912,33633,33820,38091,38673,40409,67063,157544
'Tot Fwd Pkts',,,,,,,,,,,,,,,,,,,,,
0,0,11181,16,7,10,2,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
1,49061,259,50,1,15,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
2,2935,280,57,840,97,60,228,1,0,0,...,0,0,0,0,0,0,0,0,0,0
3,932,22,673,136,166,562,7959,3,0,1,...,0,0,0,0,0,0,0,0,0,0
4,299,3,3,605,173,52,8,36543,3,4,...,0,0,0,0,0,0,0,0,0,0

In [17]:
df.groupby(["'Flow Byts/s'","'Pkt Len Std'"]).groups

{(0.0, 0.0): [2, 4, 10, 11, 12, 13, 14, 20, 21, 22, 23, 24, 30, 31, 32, 33, 34, 40, 41, 42, 43, 44, 50, 51, 52, 53, 54, 59, 61, 62, 63, 64, 70, 71, 72, 73, 74, 80, 81, 82, 83, 84, 90, 91, 92, 93, 94, 100, 101, 102, 103, 104, 110, 111, 112, 113, 114, 120, 121, 122, 123, 124, 130, 131, 132, 133, 134, 140, 141, 142, 143, 144, 150, 151, 152, 153, 154, 160, 161, 162, 163, 164, 170, 171, 172, 173, 174, 180, 181, 182, 183, 184, 190, 191, 192, 193, 194, 200, 201, 202, ...], (0.0, 13.2791): [100419, 101566, 101583, 101585, 101586, 101658, 101694, 101751, 101752, 101969, 125710, 125711, 125752], (0.0, 13.8564): [101582, 102301, 102778, 105938, 111957, 112965, 116999, 120866, 121023, 122711, 123462, 124224, 124227, 124949, 124999, 125654, 125731, 127771, 128779], (0.0, 17.8979): [101250, 101451, 101563, 101577, 101581, 101589, 101591, 101592, 101750, 102057, 102256, 102344, 104270, 123431, 123432, 123433, 123436, 123447, 123493, 123495, 123502, 123846, 123847, 123914, 123915, 124433, 124470, 124491, 124505, 124512, 124520, 124527, 124707, 124748, 124749, 124755, 124760, 124795, 124798, 124804, 124810, 124821, 124839, 124846, 124852, 124862, 124864, 124875, 124886, 124889, 124893, 124938, 124939, 124941, 124942, 124945, 124946, 124948, 124950, 124951, 124952, 124953, 125012, 125021, 125033, 125039, 125057, 125064, 125075, 125088, 125101, 125149, 125161, 125191, 125199, 125209, 125220, 125222, 125242, 125243, 125256, 125273, 125281, 125312, 125319, 125333, 125344, 125356, 125382, 125392, 125403, 125422, 125439, 125451, 125470, 125481, 125495, 125505, 125521, 125531, ...], (0.0, 18.412): [103006, 124222, 124223, 125611, 125680], (0.0, 21.9393): [102048], (0.0, 49.0748): [111221, 114718, 115884, 123480, 123776, 123777, 123778, 123779, 123780, 123781, 123782, 123784, 123785, 123786, 123789], (0.0, 133.8357): [102253], (0.0, 138.0178): [101819], (0.0, 148.9564): [125684], (0.0, 170.8957): [107540], (0.0, 237.8683): [107022], (0.0, 274.8187): [107529], (0.0, 284.0563): [102237, 107028], (0.0, 353.3384): [107532], (0.0, 376.4324): [107530], (0.0, 424.9298): [106322], (0.0, 436.4768): [106321], (0.0, 474.875): [101305], (0.0, 588.8973): [107525], (0.0111, 0.4472): [100670, 101528], (0.0111, 0.5): [100339], (0.0111, 0.5774): [100347], (0.0132, 0.4472): [100439], (0.0134, 0.4472): [101536], (0.0145, 0.4472): [106612], (0.017, 0.3153): [111658], (0.0171, 0.3008): [111530], (0.0172, 0.2881): [111760], (0.0179, 0.2881): [111928], (0.018, 0.5477): [102340], (0.0183, 0.4472): [102814, 102825, 102836, 102851, 102867, 102873, 102889, 102897, 102914, 102921, 102950, 102969, 102977, 102992, 103004, 103021, 103030, 103046, 103064, 103081, 103085, 103099, 103109, 103125, 103136, 103144, 103153, 103169, 103178, 103186, 103195, 103212, 103220, 103228, 103238, 103256, 103260, 103270, 103281, 103300, 103310, 103327, 124546, 124556, 124583, 124601, 124612], (0.0186, 0.4472): [124592], (0.0201, 0.4472): [103353], (0.0202, 0.4472): [103291], (0.0203, 0.4472): [103203, 103244], (0.0204, 0.4472): [103162], (0.0205, 0.4472): [103117], (0.0205, 0.488): [101531], (0.0206, 0.4472): [103073], (0.0207, 0.4472): [103014], (0.0209, 0.4472): [102959], (0.021, 0.4472): [102907], (0.0211, 0.4472): [102855], (0.0221, 0.5164): [101882, 102338, 102746, 102747], (0.0222, 0.5164): [100330, 100570], (0.0222, 0.5477): [100329, 100386, 100425, 100441, 100517, 100632], (0.0222, 0.5774): [101479, 101494, 101529, 102336], (0.0225, 0.5774): [124617], (0.0232, 0.5477): [101968], (0.0237, 0.5477): [115172], (0.0238, 0.5477): [115173], (0.025, 0.5345): [101749], (0.0252, 0.3317): [111874], (0.0252, 0.3586): [111635], (0.0253, 0.3317): [111609], (0.0258, 0.3444): [111911], (0.0258, 0.5774): [102339], (0.026, 0.3586): [111826], (0.0262, 0.3317): [111563], (0.0262, 0.4189): [111707], (0.0263, 0.3444): [111715], (0.0264, 0.3444): [111689], (0.0267, 0.3444): [111597], (0.0268, 0.3586): [111836], (0.0269, 0.3876): [111776], (0.027, 0.3444): [111731], (0.027, 0.5477): [103420], (0.0271, 0.3444): [111646], (0.0271, 0.3586): [111744], (0.0272, 0.3586): [111849], (0.0273, 0.3444): [111552], (0.0273, 0.3746): [111520], (0.0273, 0.4024): [111672], (0.0273, 0.5345): [101748], (0.0274, 0.5477): [112015, 128721], (0.0274, 0.5774): [102337], (0.0275, 0.3444): [111621], (0.0277, 0.4189): [111537], (0.028, 0.3203): [111573], (0.0284, 0.393): [111888], (0.0287, 0.5774): [102342], (0.0288, 0.5774): [101449], (0.0298, 0.3586): [111802], (0.0298, 0.5477): [101571], (0.0299, 0.5774): [102343], (0.0306, 0.5477): [112016, 128720], (0.0326, 0.5345): [101747], (0.0327, 0.5774): [102776], (0.0331, 0.5477): [101657, 101693], (0.0332, 0.5164): [100541, 100559, 100588, 101572], (0.0332, 0.5345): [100454, 100476, 100634, 100653, 100686, 100703, 100722, 100761, 100778, 100794, 100812, 100827, 100851, 100900, 100922, 100957, 100976, 101006, 101022, 101039, 101058, 101074, 101090, 101136, 101149, 101176, 101193, 101207, 101226, 101264, 101277, 101297, 101312, 101327, 101376, 101606, 101622, 101655, 101673, 101705, 101718, 101742, 101794, 101808, 101847, 101893, 101918, 101920, 101931, 101950, 101970, 101978, 101980, 102037, 102053, 102071, 102080, 102112, 102150, 102172, 102185, 102199, 102216, 102269, 102316, 102370, 102378, 102379, 102399, 102401, 102433, 102451, 102488, 102504, 102513, 102535, 102545, 102576, 102587, 102597, 102614, 102628, 102635, 102679, 102713, 102738, 102741, 102781, 102806, 102809, 102834, 102837, 102858, 102878, 102882, 102905, 102922, 102954, 102974, 102976, ...], (0.0333, 0.0): [101922, 101958], (0.0333, 0.4472): [100489, 106335], (0.0333, 0.5164): [106327, 112971, 127765], (0.0333, 0.5345): [100944, 101127, 101645, 101648, 101677, 101685, 101686, 101709, 101726, 101729, 101730, 101888, 101905, 101907, 101908, 101909, 101910, 101911, 101912, 101913, 101914, 101917, 101919, 101932, 101937, 101940, 101943, 101944, 101945, 101946, 101947, 101948, 101949, 101951, 101952, 101972, 101973, 101974, 101975, 101976, 101977, 101979, 102027, 102028, 102044, 102045, 102334, 102373, 102374, 102380, 102404, 102722, 102748, 102769, 102783, 102784, 102785, 102810, 102891, 103416, 103417, 103423, 103435, 103436, 103445, 104702, 104785, 104865, 105471, 106532, 106744, 106752, 107402, 107479, 107929, 108548, 108559, 108877, 108988, 109060, 109385, 109396, 109844, 110512, 110833, 110927, 110981, 111094, 111120, 111149, 111416, 112008, 112044, 112076, 112082, 112125, 112155, 112205, 112300, 112316, ...], (0.035, 0.5774): [119850], (0.0368, 0.5477): [102756], (0.037, 0.5774): [112014, 128722], (0.0382, 0.5): [101967], ...}

In [18]:
df["Label"].value_counts()

0    88502
3    28502
4    11081
1      641
2       45
5       28
Name: Label, dtype: int64

In [19]:
# Check the specific column categorical distribution
pd.Categorical(df["'Idle Min'"]).describe()

            counts     freqs
categories
0           118359  0.918943
5000007          1  0.000008
5000025          1  0.000008
5000054          1  0.000008
5000197          1  0.000008
...            ...       ...
119339118        1  0.000008
119572986        1  0.000008
119737337        1  0.000008
119754550        1  0.000008
119998794        1  0.000008

[9038 rows x 2 columns]

In [20]:
df.duplicated()

0         False
1         False
2         False
3         False
4         False
          ...
128794     True
128795     True
128796     True
128797    False
128798     True
Length: 128799, dtype: bool

In [21]:
sum(df.duplicated())

36764

In [22]:
df=df.drop_duplicates()

In [23]:
sum(df.duplicated())

0